cleanup

diff --git a/unix/.local/bin/install-ccache b/unix/.local/bin/install-ccache
--- a/unix/.local/bin/install-ccache
+++ b/unix/.local/bin/install-ccache
@@ -6,12 +6,22 @@
 
 set -e
 
-script_root="$(
-  cd "$(dirname "${BASH_SOURCE[0]}")" > /dev/null 2>&1 || exit
-  pwd -P
-)"
+declare -r reset="\033[0m"
+declare -r red="\033[0;31m"
+declare -r green="\033[0;32m"
 
-source "$script_root/../../../scripts/common.sh"
+__success() {
+  echo -e "${green}$*${reset}"
+}
+
+__error() {
+  echo -e "${red}Error: $*${reset}" 1>&2
+}
+
+__error_and_exit() {
+  echo -e "${red}Error: $*${reset}" 1>&2
+  exit 1
+}
 
 __usage() {
   cat <<EOF
@@ -61,6 +71,8 @@ __parse_parameters() {
     shift
   done
 
+  # Argument <version>
+  # Remove a single leading v
   version=${arguments[0]#v}
 
   if [[ -z $version ]]; then
diff --git a/unix/.local/bin/install-luals b/unix/.local/bin/install-luals
--- a/unix/.local/bin/install-luals
+++ b/unix/.local/bin/install-luals
@@ -1,16 +1,25 @@
 #!/usr/bin/env bash
 
 set -e
-
-script_root="$(
-  cd "$(dirname "${BASH_SOURCE[0]}")" > /dev/null 2>&1 || exit
-  pwd -P
-)"
-declare -r script_root
-
-source "$script_root/../../../scripts/common.sh"
-
 shopt -s extglob
+
+declare -r reset="\033[0m"
+declare -r red="\033[0;31m"
+declare -r green="\033[0;32m"
+declare -rl id=$(uname)
+
+__success() {
+  echo -e "${green}$*${reset}"
+}
+
+__error() {
+  echo -e "${red}Error: $*${reset}" 1>&2
+}
+
+__error_and_exit() {
+  echo -e "${red}Error: $*${reset}" 1>&2
+  exit 1
+}
 
 __usage() {
   cat <<EOF
